version: 2.1
jobs:
  build:
    docker:
      - image: cimg/android:2023.08
    steps:
      - checkout
      - run:
          name: Set Gradlew Permissions
          command: chmod +x ./gradlew
      - run:
          name: Build with Gradle
          command: ./gradlew build
workflows:
  version: 2
  build-and-test:
    jobs:
      - build