version: 2.1

jobs:
  gradle-build:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Add Permissions
          command: chmod +x ./gradlew
      - run:
          name: Build with Gradle
          command: ./gradlew bootJar
      - persist_to_workspace:
          root: .
          paths:
            - build/libs/*.jar
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - gradle-build